/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app.quickcase.sdk.spring;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
